#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches:
      - new-wifi-d2
  schedule:
    - cron: 0 20 * * *
  release:
    types: [published]

jobs:
  build_openwrt:
    name: Build OpenWrt
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # ========================固件定制部分========================
          # 

          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 

          # 以下为定制化固件选项和说明:
          #

          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #

          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 

          # 编译x64固件:
          # cat >> .config <<EOF
          # CONFIG_TARGET_x86=y
          # CONFIG_TARGET_x86_64=y
          # CONFIG_TARGET_x86_64_Generic=y
          # EOF

          # 固件压缩:
          cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_GZIP=y
          EOF

          # 编译UEFI固件:
          # cat >> .config <<EOF
          # CONFIG_EFI_IMAGES=y
          # EOF

          # IPv6支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y
          EOF

          # 多文件系统支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-fs-nfs=y
          # CONFIG_PACKAGE_kmod-fs-nfs-common=y
          # CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          # CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          # CONFIG_PACKAGE_kmod-fs-ntfs=y
          # CONFIG_PACKAGE_kmod-fs-squashfs=y
          EOF

          # USB3.0支持:
          cat >> .config <<EOF
          # CONFIG_PACKAGE_kmod-usb-ohci=y
          # CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb2=y
          # CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y
          EOF

          # 常用LuCI插件选择:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-baidupcs-web=y
          CONFIG_PACKAGE_luci-app-docker=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-kodexplorer=y
          CONFIG_PACKAGE_luci-app-minidlna=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          CONFIG_PACKAGE_luci-app-openvpn-server=y
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-v2ray-server=y
          CONFIG_PACKAGE_luci-app-verysync=y
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-wireguard=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          # EOF

          # LuCI主题:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-theme-argon=y
          # CONFIG_PACKAGE_luci-theme-netgear=y
          EOF

          # 常用软件包:
          cat >> .config <<EOF
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          # CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_screen=y
          CONFIG_PACKAGE_tree=y
          CONFIG_PACKAGE_vim-fuller=y
          CONFIG_PACKAGE_wget=y
          EOF

          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_PAD is not set
          # CONFIG_VMDK_IMAGES is not set
          EOF

          # 定制编译new-wifi-d2:
          cat >> .config <<EOF
          CONFIG_MODULES=y
          CONFIG_HAVE_DOT_CONFIG=y
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_d-team_newifi-d2=y

          #
          # Hardening build options
          #
          CONFIG_PKG_CHECK_FORMAT_SECURITY=y
          CONFIG_PKG_ASLR_PIE_REGULAR=y
          CONFIG_PKG_CC_STACKPROTECTOR_REGULAR=y
          CONFIG_KERNEL_CC_STACKPROTECTOR_REGULAR=y
          CONFIG_KERNEL_STACKPROTECTOR=y
          CONFIG_PKG_FORTIFY_SOURCE_1=y
          CONFIG_PKG_RELRO_FULL=y
          CONFIG_BINARY_FOLDER=""
          CONFIG_DOWNLOAD_FOLDER=""
          CONFIG_LOCALMIRROR=""
          CONFIG_AUTOREBUILD=y
          CONFIG_BUILD_SUFFIX=""
          CONFIG_TARGET_ROOTFS_DIR=""
          CONFIG_EXTERNAL_KERNEL_TREE=""
          CONFIG_KERNEL_GIT_CLONE_URI=""
          CONFIG_EXTRA_OPTIMIZATION="-fno-caller-saves -fno-plt"
          CONFIG_TARGET_OPTIMIZATION="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc"
          CONFIG_SOFT_FLOAT=y
          CONFIG_USE_MIPS16=y
          CONFIG_EXTRA_BINUTILS_CONFIG_OPTIONS=""
          CONFIG_EXTRA_GCC_CONFIG_OPTIONS=""
          CONFIG_GDB=y
          CONFIG_USE_MUSL=y
          CONFIG_SSP_SUPPORT=y
          CONFIG_BINUTILS_VERSION_2_31_1=y
          CONFIG_BINUTILS_VERSION="2.31.1"
          CONFIG_GCC_VERSION="7.5.0"
          CONFIG_LIBC="musl"
          CONFIG_TARGET_SUFFIX="musl"
          CONFIG_TARGET_PREINIT_SUPPRESS_STDERR=y
          CONFIG_TARGET_PREINIT_TIMEOUT=2
          CONFIG_TARGET_PREINIT_IFNAME=""
          CONFIG_TARGET_PREINIT_IP="192.168.1.1"
          CONFIG_TARGET_PREINIT_NETMASK="255.255.255.0"
          CONFIG_TARGET_PREINIT_BROADCAST="192.168.1.255"
          CONFIG_TARGET_INIT_PATH="/usr/sbin:/usr/bin:/sbin:/bin"
          CONFIG_TARGET_INIT_ENV=""
          CONFIG_TARGET_INIT_CMD="/sbin/init"
          CONFIG_TARGET_INIT_SUPPRESS_STDERR=y
          CONFIG_PER_FEED_REPO=y

          #
          # Base system
          #
          CONFIG_PACKAGE_base-files=y
          CONFIG_PACKAGE_block-mount=y
          CONFIG_PACKAGE_busybox=y
          CONFIG_PACKAGE_ca-bundle=m
          CONFIG_PACKAGE_ca-certificates=y
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_dnsmasq_full_dhcp=y
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_dnsmasq_full_ipset=y
          CONFIG_PACKAGE_dropbear=y

          #
          # Configuration
          #
          CONFIG_DROPBEAR_CURVE25519=y
          CONFIG_DROPBEAR_DBCLIENT=y
          CONFIG_PACKAGE_firewall=y
          CONFIG_PACKAGE_fstools=y
          CONFIG_FSTOOLS_UBIFS_EXTROOT=y
          CONFIG_PACKAGE_fwtool=y
          CONFIG_PACKAGE_getrandom=y
          CONFIG_PACKAGE_jsonfilter=y
          CONFIG_PACKAGE_libatomic=y
          CONFIG_PACKAGE_libc=y
          CONFIG_PACKAGE_libgcc=y
          CONFIG_PACKAGE_libpthread=y
          CONFIG_PACKAGE_librt=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_logd=y
          CONFIG_PACKAGE_mtd=y
          CONFIG_PACKAGE_netifd=y
          CONFIG_PACKAGE_opkg=y
          CONFIG_PACKAGE_procd=y

          #
          # IPV6
          #
          CONFIG_IPV6=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_kmod-ip6tables=y
          CONFIG_PACKAGE_kmod-ipt-conntrack=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-core=y
          CONFIG_PACKAGE_kmod-ipt-fullconenat=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-ipsec=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          CONFIG_PACKAGE_kmod-ipt-nat=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-ipt-offload=y
          CONFIG_PACKAGE_kmod-ipt-raw=y
          CONFIG_PACKAGE_kmod-nf-conntrack=y
          CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
          CONFIG_PACKAGE_kmod-nf-conntrack6=y
          CONFIG_PACKAGE_kmod-nf-flow=y
          CONFIG_PACKAGE_kmod-nf-ipt=y
          CONFIG_PACKAGE_kmod-nf-ipt6=y
          CONFIG_PACKAGE_kmod-nf-nat=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-nf-nathelper=y
          CONFIG_PACKAGE_kmod-nf-nathelper-extra=y
          CONFIG_PACKAGE_kmod-nf-reject=y
          CONFIG_PACKAGE_kmod-nf-reject6=y
          CONFIG_PACKAGE_kmod-nfnetlink=y
          CONFIG_PACKAGE_kmod-atm=y
          CONFIG_PACKAGE_kmod-gre=y
          CONFIG_PACKAGE_kmod-ipsec=y
          CONFIG_PACKAGE_kmod-ipsec4=y
          CONFIG_PACKAGE_kmod-ipsec6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-iptunnel6=y
          CONFIG_PACKAGE_kmod-l2tp=y
          CONFIG_PACKAGE_kmod-ppp=y
          CONFIG_PACKAGE_kmod-mppe=y
          CONFIG_PACKAGE_kmod-pppoa=y
          CONFIG_PACKAGE_kmod-pppoe=y
          CONFIG_PACKAGE_kmod-pppol2tp=y
          CONFIG_PACKAGE_kmod-pppox=y
          CONFIG_PACKAGE_kmod-pptp=y
          CONFIG_PACKAGE_kmod-sched-connmark=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_kmod-slhc=y
          CONFIG_PACKAGE_kmod-tcp-bbr=y
          CONFIG_PACKAGE_kmod-tun=y
          CONFIG_PACKAGE_kmod-udptunnel4=y
          CONFIG_PACKAGE_kmod-udptunnel6=y


          #
          # Wireless Drivers
          #
          CONFIG_PACKAGE_kmod-cfg80211=y
          CONFIG_PACKAGE_kmod-mac80211=y
          CONFIG_PACKAGE_MAC80211_DEBUGFS=y
          CONFIG_PACKAGE_MAC80211_MESH=y
          CONFIG_PACKAGE_kmod-mt76-core=y
          CONFIG_PACKAGE_kmod-mt7603=y
          CONFIG_PACKAGE_kmod-mt76x02-common=y
          CONFIG_PACKAGE_kmod-mt76x2=y
          CONFIG_PACKAGE_kmod-mt76x2-common=y

          #
          # Translations
          #
          CONFIG_LUCI_LANG_zh-cn=y
          CONFIG_PACKAGE_luci-mod-admin-full=y

          #
          # 3. Applications
          #
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-nlbwmon=y
          CONFIG_PACKAGE_luci-app-qos=y
          CONFIG_PACKAGE_luci-app-samba=y
          CONFIG_PACKAGE_luci-app-transmission=m
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-wol=y

          #
          # 5. Protocols
          #
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-proto-ppp=y

          #
          # BitTorrent
          #
          CONFIG_PACKAGE_qBittorrent=y
          CONFIG_PACKAGE_transmission-daemon-openssl=m
          CONFIG_PACKAGE_transmission-web-control=m

          #
          # Download Manager
          #
          CONFIG_PACKAGE_ariang=y
          CONFIG_PACKAGE_aria2=y
          CONFIG_ARIA2_OPENSSL=y
          CONFIG_ARIA2_NOXML=y
          CONFIG_ARIA2_BITTORRENT=y
          CONFIG_ARIA2_WEBSOCKET=y
          CONFIG_PACKAGE_wget=y

          #
          # Firewall
          #
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_iptables=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-fullconenat=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_iptables-mod-ipsec=y
          CONFIG_PACKAGE_miniupnpd=y
          CONFIG_PACKAGE_ddns-scripts=y
          CONFIG_PACKAGE_ddns-scripts_aliyun=y
          CONFIG_PACKAGE_ddns-scripts_dnspod=y

          #
          # NeteaseMusic
          #
          CONFIG_PACKAGE_UnblockNeteaseMusicGo=y
          CONFIG_PACKAGE_ip-tiny=y
          CONFIG_PACKAGE_tc=y

          #
          # SSH
          #
          CONFIG_PACKAGE_openssh-keygen=y
          CONFIG_PACKAGE_openssh-server=y

          #
          # XL2TPD
          #
          CONFIG_PACKAGE_xl2tpd=y

          #
          # Version Control Systems
          #
          CONFIG_PACKAGE_git=y

          #
          # wireless
          #
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_6to4=y
          CONFIG_PACKAGE_etherwake=y
          CONFIG_PACKAGE_hostapd-common=y
          CONFIG_PACKAGE_iw=y
          CONFIG_PACKAGE_nlbwmon=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y

          #
          # Configuration
          #
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_ppp=y
          CONFIG_PACKAGE_ppp-mod-passwordfd=y
          CONFIG_PACKAGE_ppp-mod-pppoa=y
          CONFIG_PACKAGE_ppp-mod-pppoe=y
          CONFIG_PACKAGE_ppp-mod-pppol2tp=y
          CONFIG_PACKAGE_ppp-mod-pptp=y
          CONFIG_PACKAGE_ppp-mod-radius=y
          CONFIG_PACKAGE_ppp-multilink=y
          CONFIG_PACKAGE_pppdump=y
          CONFIG_PACKAGE_pppoe-discovery=y
          CONFIG_PACKAGE_pppossh=y
          CONFIG_PACKAGE_pppstats=y
          CONFIG_PACKAGE_samba36-server=y
          CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
          CONFIG_PACKAGE_uclient-fetch=y
          CONFIG_PACKAGE_vlmcsd=y
          CONFIG_WPA_MSG_MIN_PRIORITY=3
          CONFIG_DRIVER_11N_SUPPORT=y
          CONFIG_DRIVER_11AC_SUPPORT=y
          CONFIG_DRIVER_11W_SUPPORT=y
          CONFIG_PACKAGE_wpad-openssl=y
          EOF
          # 
          # ========================固件定制部分结束========================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload config.seed
        uses: actions/upload-artifact@master
        with:
          name: config.seed
          path: ./bin/targets/*/*/config.seed

      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
